//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlovakPostApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mojezasielky.posta.sk/api", ConfigurationName="SlovakPostApi.APIPort")]
    public interface APIPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="importSheet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SlovakPostApi.importSheetResponse1> importSheetAsync(SlovakPostApi.importSheetRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSheet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SlovakPostApi.getSheetResponse1> getSheetAsync(SlovakPostApi.getSheetRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSheetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SlovakPostApi.getSheetStatusResponse1> getSheetStatusAsync(SlovakPostApi.getSheetStatusRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class importSheetRequest
    {
        
        private authType authField;
        
        private bool contractField;
        
        private bool contractFieldSpecified;
        
        private bool skipInvalidField;
        
        private bool skipInvalidFieldSpecified;
        
        private ephType ePHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public authType auth
        {
            get
            {
                return this.authField;
            }
            set
            {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool contract
        {
            get
            {
                return this.contractField;
            }
            set
            {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractSpecified
        {
            get
            {
                return this.contractFieldSpecified;
            }
            set
            {
                this.contractFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool skipInvalid
        {
            get
            {
                return this.skipInvalidField;
            }
            set
            {
                this.skipInvalidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skipInvalidSpecified
        {
            get
            {
                return this.skipInvalidFieldSpecified;
            }
            set
            {
                this.skipInvalidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ephType EPH
        {
            get
            {
                return this.ePHField;
            }
            set
            {
                this.ePHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mojezasielky.posta.sk/api")]
    public partial class authType
    {
        
        private string userIdField;
        
        private string apiKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string apiKey
        {
            get
            {
                return this.apiKeyField;
            }
            set
            {
                this.apiKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephType
    {
        
        private ephTypeInfoEPH infoEPHField;
        
        private ephTypeZasielka[] zasielkyField;
        
        private string verziaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ephTypeInfoEPH InfoEPH
        {
            get
            {
                return this.infoEPHField;
            }
            set
            {
                this.infoEPHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Zasielka", IsNullable=false)]
        public ephTypeZasielka[] Zasielky
        {
            get
            {
                return this.zasielkyField;
            }
            set
            {
                this.zasielkyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verzia
        {
            get
            {
                return this.verziaField;
            }
            set
            {
                this.verziaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeInfoEPH
    {
        
        private string menaField;
        
        private string typEPHField;
        
        private string ePHIDField;
        
        private string datumField;
        
        private string pocetZasielokField;
        
        private ephTypeInfoEPHUhrada[] uhradaField;
        
        private string druhPPPField;
        
        private string druhZasielkyField;
        
        private string sposobSpracovaniaField;
        
        private ephTypeInfoEPHOdosielatel odosielatelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mena
        {
            get
            {
                return this.menaField;
            }
            set
            {
                this.menaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string TypEPH
        {
            get
            {
                return this.typEPHField;
            }
            set
            {
                this.typEPHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EPHID
        {
            get
            {
                return this.ePHIDField;
            }
            set
            {
                this.ePHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PocetZasielok
        {
            get
            {
                return this.pocetZasielokField;
            }
            set
            {
                this.pocetZasielokField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Uhrada", Order=5)]
        public ephTypeInfoEPHUhrada[] Uhrada
        {
            get
            {
                return this.uhradaField;
            }
            set
            {
                this.uhradaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=6)]
        public string DruhPPP
        {
            get
            {
                return this.druhPPPField;
            }
            set
            {
                this.druhPPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=7)]
        public string DruhZasielky
        {
            get
            {
                return this.druhZasielkyField;
            }
            set
            {
                this.druhZasielkyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=8)]
        public string SposobSpracovania
        {
            get
            {
                return this.sposobSpracovaniaField;
            }
            set
            {
                this.sposobSpracovaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ephTypeInfoEPHOdosielatel Odosielatel
        {
            get
            {
                return this.odosielatelField;
            }
            set
            {
                this.odosielatelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeInfoEPHUhrada
    {
        
        private string sposobUhradyField;
        
        private string sumaUhradyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string SposobUhrady
        {
            get
            {
                return this.sposobUhradyField;
            }
            set
            {
                this.sposobUhradyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SumaUhrady
        {
            get
            {
                return this.sumaUhradyField;
            }
            set
            {
                this.sumaUhradyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeInfoEPHOdosielatel
    {
        
        private string odosielatelIDField;
        
        private string menoField;
        
        private string organizaciaField;
        
        private string ulicaField;
        
        private string mestoField;
        
        private string pSCField;
        
        private string krajinaField;
        
        private string telefonField;
        
        private string emailField;
        
        private string cisloUctuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OdosielatelID
        {
            get
            {
                return this.odosielatelIDField;
            }
            set
            {
                this.odosielatelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Meno
        {
            get
            {
                return this.menoField;
            }
            set
            {
                this.menoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Organizacia
        {
            get
            {
                return this.organizaciaField;
            }
            set
            {
                this.organizaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Mesto
        {
            get
            {
                return this.mestoField;
            }
            set
            {
                this.mestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PSC
        {
            get
            {
                return this.pSCField;
            }
            set
            {
                this.pSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Krajina
        {
            get
            {
                return this.krajinaField;
            }
            set
            {
                this.krajinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Telefon
        {
            get
            {
                return this.telefonField;
            }
            set
            {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CisloUctu
        {
            get
            {
                return this.cisloUctuField;
            }
            set
            {
                this.cisloUctuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielka
    {
        
        private ephTypeZasielkaAdresat adresatField;
        
        private ephTypeZasielkaSpat spatField;
        
        private ephTypeZasielkaInfo infoField;
        
        private string[] pouziteSluzbyField;
        
        private ephTypeZasielkaUdaj[] dalsieUdajeField;
        
        private ephTypeZasielkaColneVyhlasenie colneVyhlasenieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ephTypeZasielkaAdresat Adresat
        {
            get
            {
                return this.adresatField;
            }
            set
            {
                this.adresatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ephTypeZasielkaSpat Spat
        {
            get
            {
                return this.spatField;
            }
            set
            {
                this.spatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ephTypeZasielkaInfo Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sluzba", IsNullable=false)]
        public string[] PouziteSluzby
        {
            get
            {
                return this.pouziteSluzbyField;
            }
            set
            {
                this.pouziteSluzbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Udaj", IsNullable=false)]
        public ephTypeZasielkaUdaj[] DalsieUdaje
        {
            get
            {
                return this.dalsieUdajeField;
            }
            set
            {
                this.dalsieUdajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ephTypeZasielkaColneVyhlasenie ColneVyhlasenie
        {
            get
            {
                return this.colneVyhlasenieField;
            }
            set
            {
                this.colneVyhlasenieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaAdresat
    {
        
        private string menoField;
        
        private string organizaciaField;
        
        private string ulicaField;
        
        private string mestoField;
        
        private string pSCField;
        
        private string krajinaField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Meno
        {
            get
            {
                return this.menoField;
            }
            set
            {
                this.menoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Organizacia
        {
            get
            {
                return this.organizaciaField;
            }
            set
            {
                this.organizaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mesto
        {
            get
            {
                return this.mestoField;
            }
            set
            {
                this.mestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PSC
        {
            get
            {
                return this.pSCField;
            }
            set
            {
                this.pSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Krajina
        {
            get
            {
                return this.krajinaField;
            }
            set
            {
                this.krajinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Telefon
        {
            get
            {
                return this.telefonField;
            }
            set
            {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaSpat
    {
        
        private string menoField;
        
        private string organizaciaField;
        
        private string ulicaField;
        
        private string mestoField;
        
        private string pSCField;
        
        private string krajinaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Meno
        {
            get
            {
                return this.menoField;
            }
            set
            {
                this.menoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Organizacia
        {
            get
            {
                return this.organizaciaField;
            }
            set
            {
                this.organizaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mesto
        {
            get
            {
                return this.mestoField;
            }
            set
            {
                this.mestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PSC
        {
            get
            {
                return this.pSCField;
            }
            set
            {
                this.pSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Krajina
        {
            get
            {
                return this.krajinaField;
            }
            set
            {
                this.krajinaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaInfo
    {
        
        private string ciarovyKodField;
        
        private string zasielkaIDField;
        
        private string hmotnostField;
        
        private string cenaDobierkyField;
        
        private string cenaPoistnehoField;
        
        private string cenaVyplatnehoField;
        
        private string triedaField;
        
        private string cisloUctuField;
        
        private string symbolPrevoduField;
        
        private string poznamkaField;
        
        private string druhPPPField;
        
        private string druhZasielkyField;
        
        private string datumPrijatiaField;
        
        private string objemField;
        
        private string pocetKusovField;
        
        private string obsahZasielkyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CiarovyKod
        {
            get
            {
                return this.ciarovyKodField;
            }
            set
            {
                this.ciarovyKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ZasielkaID
        {
            get
            {
                return this.zasielkaIDField;
            }
            set
            {
                this.zasielkaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Hmotnost
        {
            get
            {
                return this.hmotnostField;
            }
            set
            {
                this.hmotnostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CenaDobierky
        {
            get
            {
                return this.cenaDobierkyField;
            }
            set
            {
                this.cenaDobierkyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CenaPoistneho
        {
            get
            {
                return this.cenaPoistnehoField;
            }
            set
            {
                this.cenaPoistnehoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CenaVyplatneho
        {
            get
            {
                return this.cenaVyplatnehoField;
            }
            set
            {
                this.cenaVyplatnehoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Trieda
        {
            get
            {
                return this.triedaField;
            }
            set
            {
                this.triedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CisloUctu
        {
            get
            {
                return this.cisloUctuField;
            }
            set
            {
                this.cisloUctuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SymbolPrevodu
        {
            get
            {
                return this.symbolPrevoduField;
            }
            set
            {
                this.symbolPrevoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Poznamka
        {
            get
            {
                return this.poznamkaField;
            }
            set
            {
                this.poznamkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=10)]
        public string DruhPPP
        {
            get
            {
                return this.druhPPPField;
            }
            set
            {
                this.druhPPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=11)]
        public string DruhZasielky
        {
            get
            {
                return this.druhZasielkyField;
            }
            set
            {
                this.druhZasielkyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DatumPrijatia
        {
            get
            {
                return this.datumPrijatiaField;
            }
            set
            {
                this.datumPrijatiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Objem
        {
            get
            {
                return this.objemField;
            }
            set
            {
                this.objemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=14)]
        public string PocetKusov
        {
            get
            {
                return this.pocetKusovField;
            }
            set
            {
                this.pocetKusovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ObsahZasielky
        {
            get
            {
                return this.obsahZasielkyField;
            }
            set
            {
                this.obsahZasielkyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaUdaj
    {
        
        private string nazovField;
        
        private string hodnotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nazov
        {
            get
            {
                return this.nazovField;
            }
            set
            {
                this.nazovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Hodnota
        {
            get
            {
                return this.hodnotaField;
            }
            set
            {
                this.hodnotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaColneVyhlasenie
    {
        
        private string kategoriaField;
        
        private string kategoriaIneField;
        
        private ephTypeZasielkaColneVyhlaseniePolozka[] obsahField;
        
        private ephTypeZasielkaColneVyhlasenieDokument[] dokumentyField;
        
        private string referenciaDovozcuField;
        
        private string poznamkaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Kategoria
        {
            get
            {
                return this.kategoriaField;
            }
            set
            {
                this.kategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KategoriaIne
        {
            get
            {
                return this.kategoriaIneField;
            }
            set
            {
                this.kategoriaIneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Polozka", IsNullable=false)]
        public ephTypeZasielkaColneVyhlaseniePolozka[] Obsah
        {
            get
            {
                return this.obsahField;
            }
            set
            {
                this.obsahField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Dokument", IsNullable=false)]
        public ephTypeZasielkaColneVyhlasenieDokument[] Dokumenty
        {
            get
            {
                return this.dokumentyField;
            }
            set
            {
                this.dokumentyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReferenciaDovozcu
        {
            get
            {
                return this.referenciaDovozcuField;
            }
            set
            {
                this.referenciaDovozcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Poznamka
        {
            get
            {
                return this.poznamkaField;
            }
            set
            {
                this.poznamkaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaColneVyhlaseniePolozka
    {
        
        private string popisField;
        
        private string mnozstvoField;
        
        private string hmotnostField;
        
        private string hodnotaField;
        
        private string tarifneCisloField;
        
        private string krajinaPovoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Popis
        {
            get
            {
                return this.popisField;
            }
            set
            {
                this.popisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string Mnozstvo
        {
            get
            {
                return this.mnozstvoField;
            }
            set
            {
                this.mnozstvoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Hmotnost
        {
            get
            {
                return this.hmotnostField;
            }
            set
            {
                this.hmotnostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Hodnota
        {
            get
            {
                return this.hodnotaField;
            }
            set
            {
                this.hodnotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TarifneCislo
        {
            get
            {
                return this.tarifneCisloField;
            }
            set
            {
                this.tarifneCisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string KrajinaPovodu
        {
            get
            {
                return this.krajinaPovoduField;
            }
            set
            {
                this.krajinaPovoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class ephTypeZasielkaColneVyhlasenieDokument
    {
        
        private string typField;
        
        private string cisloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Typ
        {
            get
            {
                return this.typField;
            }
            set
            {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cislo
        {
            get
            {
                return this.cisloField;
            }
            set
            {
                this.cisloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class importSheetResponse
    {
        
        private string sheetIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sheetId
        {
            get
            {
                return this.sheetIdField;
            }
            set
            {
                this.sheetIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importSheetRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mojezasielky.posta.sk/api", Order=0)]
        public SlovakPostApi.importSheetRequest importSheetRequest;
        
        public importSheetRequest1()
        {
        }
        
        public importSheetRequest1(SlovakPostApi.importSheetRequest importSheetRequest)
        {
            this.importSheetRequest = importSheetRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importSheetResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mojezasielky.posta.sk/api", Order=0)]
        public SlovakPostApi.importSheetResponse importSheetResponse;
        
        public importSheetResponse1()
        {
        }
        
        public importSheetResponse1(SlovakPostApi.importSheetResponse importSheetResponse)
        {
            this.importSheetResponse = importSheetResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class getSheetRequest
    {
        
        private authType authField;
        
        private string sheetIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public authType auth
        {
            get
            {
                return this.authField;
            }
            set
            {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sheetId
        {
            get
            {
                return this.sheetIdField;
            }
            set
            {
                this.sheetIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class getSheetResponse
    {
        
        private string sheetStatusField;
        
        private ephType ePHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sheetStatus
        {
            get
            {
                return this.sheetStatusField;
            }
            set
            {
                this.sheetStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ephType EPH
        {
            get
            {
                return this.ePHField;
            }
            set
            {
                this.ePHField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSheetRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mojezasielky.posta.sk/api", Order=0)]
        public SlovakPostApi.getSheetRequest getSheetRequest;
        
        public getSheetRequest1()
        {
        }
        
        public getSheetRequest1(SlovakPostApi.getSheetRequest getSheetRequest)
        {
            this.getSheetRequest = getSheetRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSheetResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mojezasielky.posta.sk/api", Order=0)]
        public SlovakPostApi.getSheetResponse getSheetResponse;
        
        public getSheetResponse1()
        {
        }
        
        public getSheetResponse1(SlovakPostApi.getSheetResponse getSheetResponse)
        {
            this.getSheetResponse = getSheetResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class getSheetStatusRequest
    {
        
        private authType authField;
        
        private string sheetIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public authType auth
        {
            get
            {
                return this.authField;
            }
            set
            {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sheetId
        {
            get
            {
                return this.sheetIdField;
            }
            set
            {
                this.sheetIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class getSheetStatusResponse
    {
        
        private string sheetStatusField;
        
        private sheetErrorReportTypeError[] sheetErrorReportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sheetStatus
        {
            get
            {
                return this.sheetStatusField;
            }
            set
            {
                this.sheetStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
        public sheetErrorReportTypeError[] sheetErrorReport
        {
            get
            {
                return this.sheetErrorReportField;
            }
            set
            {
                this.sheetErrorReportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mojezasielky.posta.sk/api")]
    public partial class sheetErrorReportTypeError
    {
        
        private string attrField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSheetStatusRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mojezasielky.posta.sk/api", Order=0)]
        public SlovakPostApi.getSheetStatusRequest getSheetStatusRequest;
        
        public getSheetStatusRequest1()
        {
        }
        
        public getSheetStatusRequest1(SlovakPostApi.getSheetStatusRequest getSheetStatusRequest)
        {
            this.getSheetStatusRequest = getSheetStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSheetStatusResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mojezasielky.posta.sk/api", Order=0)]
        public SlovakPostApi.getSheetStatusResponse getSheetStatusResponse;
        
        public getSheetStatusResponse1()
        {
        }
        
        public getSheetStatusResponse1(SlovakPostApi.getSheetStatusResponse getSheetStatusResponse)
        {
            this.getSheetStatusResponse = getSheetStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface APIPortChannel : SlovakPostApi.APIPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class APIPortClient : System.ServiceModel.ClientBase<SlovakPostApi.APIPort>, SlovakPostApi.APIPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public APIPortClient() : 
                base(APIPortClient.GetDefaultBinding(), APIPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.APISoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIPortClient(EndpointConfiguration endpointConfiguration) : 
                base(APIPortClient.GetBindingForEndpoint(endpointConfiguration), APIPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(APIPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(APIPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SlovakPostApi.importSheetResponse1> SlovakPostApi.APIPort.importSheetAsync(SlovakPostApi.importSheetRequest1 request)
        {
            return base.Channel.importSheetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SlovakPostApi.importSheetResponse1> importSheetAsync(SlovakPostApi.importSheetRequest importSheetRequest)
        {
            SlovakPostApi.importSheetRequest1 inValue = new SlovakPostApi.importSheetRequest1();
            inValue.importSheetRequest = importSheetRequest;
            return ((SlovakPostApi.APIPort)(this)).importSheetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SlovakPostApi.getSheetResponse1> SlovakPostApi.APIPort.getSheetAsync(SlovakPostApi.getSheetRequest1 request)
        {
            return base.Channel.getSheetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SlovakPostApi.getSheetResponse1> getSheetAsync(SlovakPostApi.getSheetRequest getSheetRequest)
        {
            SlovakPostApi.getSheetRequest1 inValue = new SlovakPostApi.getSheetRequest1();
            inValue.getSheetRequest = getSheetRequest;
            return ((SlovakPostApi.APIPort)(this)).getSheetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SlovakPostApi.getSheetStatusResponse1> SlovakPostApi.APIPort.getSheetStatusAsync(SlovakPostApi.getSheetStatusRequest1 request)
        {
            return base.Channel.getSheetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SlovakPostApi.getSheetStatusResponse1> getSheetStatusAsync(SlovakPostApi.getSheetStatusRequest getSheetStatusRequest)
        {
            SlovakPostApi.getSheetStatusRequest1 inValue = new SlovakPostApi.getSheetStatusRequest1();
            inValue.getSheetStatusRequest = getSheetStatusRequest;
            return ((SlovakPostApi.APIPort)(this)).getSheetStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.APISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.APISoap))
            {
                return new System.ServiceModel.EndpointAddress("https://mojezasielky.posta.sk/integration/webServices/api");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return APIPortClient.GetBindingForEndpoint(EndpointConfiguration.APISoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return APIPortClient.GetEndpointAddress(EndpointConfiguration.APISoap);
        }
        
        public enum EndpointConfiguration
        {
            
            APISoap,
        }
    }
}
